export default {
  container: {
    display: "flex",
    width: "95%",
    marginLeft: "auto",
    marginRight: "auto",
    border: "1px solid white",
    borderRadius: 10,
    marginTop: "2%",
    overflowY: "scroll",
    flexDirection: "column",
  },
  title_text: {
    color: "white",
    fontSize: 20,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: "1%",
  },
  des_text: {
    color: "white",
    fontSize: 18,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: "1%",
    textAlign: "center",
  },
  name_email_view: {
    display: "flex",
    width: "50%",
    //border: "1px solid white",
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: "1%",
    alignItems: "center",
  },
  button: {
    backgroundColor: "#4b6cc1",
    borderColor: "white",
    color: "white",
    borderRadius: "100px",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: "1%",
    width: "22%",
  },
  spinner: {
    marginLeft: "5%",
    marginBottom: "4%",
  },
};
