export default {
  container: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    height: "100vh",
  },
  des_view: {
    display: "flex",
    flex: 0.55,
    alignSelf: "center",
    alignItems: "center",
    width: "80vw",
    //border: "2px solid red",
    justifyContent: "center",
    flexDirection: "column",
  },
  title_text: {
    color: "white",
    fontSize: 22,
    fontWeight: "bold",
    alignSelf: "center",
    marginBottom: "5%",
  },
  header_text: {
    color: "white",
    fontSize: 19,
    fontWeight: "bold",
    alignSelf: "flex-start",
  },
  des_text: {
    color: "white",
    fontSize: 18,
  },
  img_social_button_view: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    flex: 0.3,
    //width: "20vw",
    alignSelf: "center",
    //border: "2px solid red",
    flexDirection: "column",
  },
  line: {
    display: "flex",
    width: "100%",
    marginTop: "1%",
    borderBottom: "2px solid white",
  },
  button_view: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "50%",
    marginTop: "1%",
    //borderBottom: "2px solid white",
  },
};
